import pandas as pd

from czsc import Freq as Freq
from czsc import RawBar as RawBar

def _to_bs_code(symbol: str) -> str: ...
def _freq_to_bs(freq: Freq) -> str: ...
def _fq_to_bs(fq: str) -> str: ...
def format_kline(kline: pd.DataFrame, freq: Freq) -> list[RawBar]: ...
def get_symbols(day: str = "", **kwargs) -> list[str]: ...
def get_raw_bars(symbol, freq, sdt, edt, fq: str = "前复权", raw_bar: bool = True, **kwargs): ...
